
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podtato-head-keptn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ottolote/keptn-argocd-config.git
    targetRevision: HEAD
    path: .
    directory:
      include: podtato-head-keptn-app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: podtato-head
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
